"""astronaute complet

Revision ID: 1a1b57f78b6b
Revises: 8e269527e4c2
Create Date: 2026-09-23 10:55:37.167859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1b57f78b6b'
down_revision: Union[str, Sequence[str], None] = '8e269527e4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated par Alembic - ajuste a la main ###
    # server_default requis : la table contient deja une ligne (astronaute de
    # test cree par /ingest), une colonne NOT NULL sans defaut ferait echouer
    # la migration sur la base existante.
    op.add_column(
        'astronautes',
        sa.Column('role', sa.String(length=80), nullable=False, server_default=''),
    )
    op.add_column(
        'astronautes',
        sa.Column('initiales', sa.String(length=4), nullable=False, server_default=''),
    )
    op.add_column(
        'astronautes',
        sa.Column('sol_embarquement', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astronautes', 'sol_embarquement')
    op.drop_column('astronautes', 'initiales')
    op.drop_column('astronautes', 'role')
    # ### end Alembic commands ###
