"""empreinte faciale de l'astronaute

Revision ID: 5f6851ca19a9
Revises: 8cae106a23e7
Create Date: 2026-09-23 11:31:36.040700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6851ca19a9'
down_revision: Union[str, Sequence[str], None] = '8cae106a23e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable, sans server_default : la table contient deja des lignes, mais
    # aucune n'a jamais ete enrolee avec une empreinte faciale (donnee
    # biometrique - voir app/models/tables.py::Astronaute.empreinte_faciale),
    # donc NULL est la seule valeur honnete pour elles.
    op.add_column('astronautes', sa.Column('empreinte_faciale', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('astronautes', 'empreinte_faciale')
    # ### end Alembic commands ###
