"""persistance des decisions et du consentement cabine

Revision ID: 8cae106a23e7
Revises: 7c9eee2ae359
Create Date: 2026-09-23 11:16:43.156261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cae106a23e7'
down_revision: Union[str, Sequence[str], None] = '7c9eee2ae359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentements_cabine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabine_id', sa.String(length=50), nullable=False),
    sa.Column('camera', sa.Boolean(), nullable=False),
    sa.Column('microphone', sa.Boolean(), nullable=False),
    sa.Column('maj', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cabine_id')
    )
    # Pas de server_default sur assessment_id malgre le NOT NULL : la table
    # `decisions` est vide a ce jour (rien n'y persistait avant cette tache),
    # donc l'ALTER TABLE ne viole aucune ligne existante. Un server_default
    # aurait de toute facon ete faux ici : une valeur partagee entre
    # plusieurs lignes casserait l'index unique cree juste apres. Si cette
    # migration est un jour rejouee sur une base deja peuplee de decisions,
    # il faudra d'abord backfiller assessment_id ligne par ligne (uuid4() par
    # exemple) avant de poser le NOT NULL + UNIQUE.
    op.add_column('decisions', sa.Column('assessment_id', sa.String(length=36), nullable=False))
    op.add_column('decisions', sa.Column('exercice_id', sa.String(length=50), nullable=True))
    op.add_column('decisions', sa.Column('feedback', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_decisions_assessment_id'), 'decisions', ['assessment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_assessment_id'), table_name='decisions')
    op.drop_column('decisions', 'feedback')
    op.drop_column('decisions', 'exercice_id')
    op.drop_column('decisions', 'assessment_id')
    op.drop_table('consentements_cabine')
    # ### end Alembic commands ###
